// I'll explicitly write all of these for clarity
export default {
    allKeys: [
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
    ],
    leftCenter: ['A', 'S', 'D', 'F', 'G'],
    rightCenter: ['H'],
};
